spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=username
spring.mail.password=password
spring.mail.properties.mail.smtp.trust="*"
spring.mail.properties.mail.auth= true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.connectiontimeout=5000
spring.mail.properties.mail.timeout=3000
spring.mail.properties.writetimeout=5000

application.security.jwt.secret-key=3YzVwtrgaCVtVS8wbg5ZYSVpUhd11cvThXTANlqRcQ4qL0o/puE1cbvHKwN8ecl/
# 0A0486EBF19DB7AA36FECD29D6F4D635674692E7E5BD757F8BE32346CC7FCE1E
application.security.jwt.expiration=86400000

application.email.frontend.confirmation-url=http://localhost:4200/activate_account

application.file.upload.photos.output-path= ./uploads